version: "3"
services:
  agent:
    # replace username/repo:tag with your name and image details
    image: hocx3/docker_stats:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
        - PORT=4000
        - HOST_ID=192.168.99.100
        - TIME_POST=30
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
      - webnet
networks:
  webnet: